### ISSUE TITLE
Parser to parse Edit Command

### ISSUE THREAD

**Issue by VerbalCriminal** [cs2103jan2016-W14-2J/main#47]
Currently, edit parser cannot parse command like "edit from yishun to sembawang".

**Comment by yanglu758** [comment]
Can
1. Edit 1 from {new start time} to {new end time}
2. Edit 1 from {new start time}.
3. Edit 1 to {new end time}.
4. Edit 1 {new task name}.

**Comment by yanglu758** [comment]
BUG: EVENT_TIME
![capture](https://cloud.githubusercontent.com/assets/12844206/14040883/af86e90a-f2a6-11e5-817d-0bde2bcad4c1.JPG)
