### ISSUE TITLE
Parser to support abbreviation

### ISSUE THREAD

**Issue by yanglu758** [cs2103jan2016-W14-2J/main#50]

**Comment by VerbalCriminal** [comment]
example: add meet luyang tomorrow
current parser only accepts add meet luyang <prepositions> tomorrow.

**Comment by young07ly** [comment]
- Tomorrow: tml, tmr, tmrw
- Don't need 'by tmrw', just 'tmrw'

**Comment by yanglu758** [comment]
Can:
1. Tomorrow: tmrw, tml, tmr, 2mr, 2moro
2. Today: tdy
3. Monday, Tuesday etc.
4. January, February etc. 

Cannot
1. Yesterday
2. Without proposition e.g. by tmrw -> tmrw;
