### ISSUE TITLE
Parser to enhance Search

### ISSUE THREAD

**Issue by yanglu758** [cs2103jan2016-W14-2J/main#84]
Parser to return 
1) enum COMMAND_TYPE type = parser.getCommandType();
2) enum SEARCH_TYPE search_type = parser.getSearchType();
3) case STRING: String search_string = parser.getSearchString();
4) case DATE: Date date = parser.getSearchDate();

**Comment by yanglu758** [comment]
1. search by keyword - done
2. search by tag - done
3. search by specific date - done 

ENHANCEMENT
4. search by a day in week e.g. search Thursday
5. search by a specific time e.g. search 3pm
6. search by a month e.g. search January
7. search by a year e.g. search 2017

TO BE DISCUSSED

**Comment by VerbalCriminal** [comment]
You can simply retrieve the date and time element from my date object and do an in-depth search

**Comment by VerbalCriminal** [comment]
Propose to use #thursday# to indicate word as a keyword instead of a date.
